[package]
name = "kernelport-backend-ort"
version = "0.0.0"
edition = "2021"

[dependencies]
anyhow = "1"
bytes = "1"
kernelport-core = { path = "../kernelport-core" }
ort = { version = "2.0.0-rc.10", features = ["download-binaries"] }

[features]
cuda = ["ort/cuda"]
